src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Gedmo\Mapping\Annotation as Gedmo;

//use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    const ROLE_DEFAULT = 'ROLE_USER';

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    private $newPassword;

    /**
     * @ORM\Column(type="string", length=127)
     * @var string
     * salt used to encrypt/dectrypt master key
     */
    protected $keySalt;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $encryptedMasterKey;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\ManyToMany(targetEntity="Role")
     * @ORM\JoinColumn(onDelete="CASCADE")
     * @ORM\JoinTable(name="user_roles")
     */
    protected $rolesAssigned;

    /**
     * @ORM\Column(type="string", length=127)
     * @var string
     * ciphr method and mode selection
     */
    protected $cipherMethod;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer", nullable=false)
     */
    private $masterKeyLength;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="created", type="datetime", nullable=false)
     * @Gedmo\Timestampable(on="create")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    protected $updated;


    public function __construct()
    {
        $this->isActive = true;
        $this->rolesAssigned = new ArrayCollection();
        $this->cipherMethod = 'aes-256-cbc';
        $this->masterKeyLength = 512;
        // may not be needed, see section on salt below
        // $this->salt = md5(uniqid('', true));
        $this->keySalt = bin2hex(openssl_random_pseudo_bytes(16));
    }

    public function __toString()
    {
        return $this->getUsername();
    }

    public function generateMasterKey()
    {
        $iv_dec = openssl_random_pseudo_bytes($this->getMasterKeyLength());
        return $iv_dec;
    }

    public function convertPasswordIntoUserKey($plainPassword)
    {
        return hash('sha512', hex2bin($this->keySalt).$plainPassword);
    }

    /**
     * string decryption function
     * @param string $what
     * @param string $key
     * @return string
     * @author Jakub Reiter
     */
    public function encrypt($what, $key)
    {
        $iv_size = openssl_cipher_iv_length($this->getCipherMethod());
        $iv_dec = openssl_random_pseudo_bytes($iv_size);
        $ciphertext = openssl_encrypt($what, $this->getCipherMethod(), $key, OPENSSL_RAW_DATA, $iv_dec);
        $ciphertext = $iv_dec . $ciphertext;

        return bin2hex($ciphertext);
    }

    /**
     * string encryption function
     * @param string $what
     * @param string $key
     * @return string
     * @author Jakub Reiter
     */
    public function decrypt($what, string $key)
    {
        $iv_size = openssl_cipher_iv_length($this->getCipherMethod());

        $ciphertext_dec = hex2bin($what);
        $iv_dec = substr($ciphertext_dec, 0, $iv_size);
        $ciphertext_dec = substr($ciphertext_dec, $iv_size);

        return openssl_decrypt($ciphertext_dec, $this->getCipherMethod(), $key, OPENSSL_RAW_DATA, $iv_dec);
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function getRoles()
    {
        $roleCollection = $this->getRolesAssigned();
        $rArray = [];
        foreach ($roleCollection as $AssRole) {
            $rArray[] = $AssRole->getName();
        }
        return $rArray;
        //return array('ROLE_USER');
    }

    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->isActive;
    }

    /**
     * @return Collection|Role[]
     */
    public function getRolesAssigned(): Collection
    {
        return $this->rolesAssigned;
    }

    public function addRolesAssigned(Role $rolesAssigned): self
    {
        if (!$this->rolesAssigned->contains($rolesAssigned)) {
            $this->rolesAssigned[] = $rolesAssigned;
        }

        return $this;
    }

    public function removeRolesAssigned(Role $rolesAssigned): self
    {
        if ($this->rolesAssigned->contains($rolesAssigned)) {
            $this->rolesAssigned->removeElement($rolesAssigned);
        }

        return $this;
    }

    public function getNewPassword(): ?string
    {
        return $this->newPassword;
    }

    public function setNewPassword(string $newPassword): self
    {
        $this->newPassword = $newPassword;

        return $this;
    }

    public function getEncryptedMasterKey(): ?string
    {
        return $this->encryptedMasterKey;
    }

    public function setEncryptedMasterKey(?string $encryptedMasterKey): self
    {
        $this->encryptedMasterKey = $encryptedMasterKey;

        return $this;
    }

    public function getDecryptedMasterKey(string $key): ?string
    {
        $emc = $this->decrypt($this->encryptedMasterKey, $key);
        return $emc;
    }

    public function getCipherMethod(): ?string
    {
        return $this->cipherMethod;
    }

    public function setCipherMethod(string $cipherMethod): self
    {
        $this->cipherMethod = $cipherMethod;

        return $this;
    }

    public function getMasterKeyLength(): ?int
    {
        return $this->masterKeyLength;
    }

    public function setMasterKeyLength(int $masterKeyLength): self
    {
        $this->masterKeyLength = $masterKeyLength;

        return $this;
    }

    public function getKeySalt(): ?string
    {
        return $this->keySalt;
    }

    public function setKeySalt(string $keySalt): self
    {
        $this->keySalt = $keySalt;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')

            ->add('email')
            ->add('isActive')
            ->add('rolesAssigned')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,

        ]);
    }
}

src/Controller/UserController.php
<?php
namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Form\UserNewType;
use App\Form\UserPassType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/admin/user")
 */
class UserController extends Controller
{

	/**
	 * @Route("/", name="user_index", methods="GET")
	 */
	public function index(Request $request, UserRepository $userRepository): Response
	{
	    // dump($request->server->getHeaders()['PHP_AUTH_PW']);
		return $this->render('user/index.html.twig', [
			'users' => $userRepository->findAll()
		]);
	}

	/**
	 * @Route("/new", name="user_new", methods="GET|POST")
	 */
	public function new(Request $request, UserPasswordEncoderInterface $encoder): Response
	{
        /**
         * @var User $loggedInUser
         */
        $loggedInUser = $this->getUser();
		$user = new User();
		$form = $this->createForm(UserNewType::class, $user);
		$form->handleRequest($request);
		
		if ($form->isSubmitted() && $form->isValid()) {

            $passwordOfLoggedInUser = $request->headers->get('php-auth-pw');
            if (!$passwordOfLoggedInUser) return $this->render('security/no_user_pw.html.twig');
            $userKey =  $loggedInUser->convertPasswordIntoUserKey($passwordOfLoggedInUser);
            $masterKey =  $loggedInUser->decrypt( $loggedInUser->getEncryptedMasterKey(),  $userKey);
            unset($passwordOfLoggedInUser);
            $user->setEncryptedMasterKey( $user->encrypt($masterKey, $user->convertPasswordIntoUserKey($user->getNewPassword()))  );

			$encoded = $encoder->encodePassword($user, $user->getNewPassword());
			$user->setPassword($encoded);
			$em = $this->getDoctrine()->getManager();
			$em->persist($user);
			$em->flush();
			// commented to avoid session -- $this->addFlash('success', 'User created.');
			return $this->redirectToRoute('user_index');
		}
		
		return $this->render('user/new.html.twig', [
			'user' => $user,
			'form' => $form->createView()
		]);
	}

	/**
	 * @Route("/{id}", name="user_show", methods="GET")
	 */
	public function show(User $user): Response
	{

	    $key = $user->convertPasswordIntoUserKey('pasikonik2019');

	    $masterKey = $user->decrypt($user->getEncryptedMasterKey(), $key);

		return $this->render('user/show.html.twig', [
			'user' => $user
		]);
	}

	/**
	 * @Route("/{id}/edit", name="user_edit", methods="GET|POST")
	 */
	public function edit(Request $request, User $user): Response
	{
		$form = $this->createForm(UserType::class, $user);
		$form->handleRequest($request);
		
		if ($form->isSubmitted() && $form->isValid()) {
			$this->getDoctrine()
				->getManager()
				->flush();
            // commented to avoid session -- $this->addFlash('success', 'Saved.');
			return $this->redirectToRoute('user_index');
		}
		
		return $this->render('user/edit.html.twig', [
			'user' => $user,
			'form' => $form->createView()
		]);
	}

    /**
     * @Route("/me/change_my_pass", name="user_change_my_pass", methods="GET")
     */
    public function changeMyPassword(Request $request): Response
    {

        return $this->redirectToRoute('user_change_pass', [
            'id' => $this->getUser()->getId()
        ]);
    }

	/**
	 * @Route("/{id}/change_pass", name="user_change_pass", methods="GET|POST")
	 */
	public function changePassword(Request $request, User $user, UserPasswordEncoderInterface $encoder): Response
	{
		$form = $this->createForm(UserPassType::class, $user);
		$form->handleRequest($request);
		
		if ($form->isSubmitted() && $form->isValid()) {

            $loggedInUser = $this->getUser();

			$plainPassword = $user->getNewPassword();

            $passwordOfLoggedInUser = $request->headers->get('php-auth-pw');
            if (!$passwordOfLoggedInUser) return $this->render('security/no_user_pw.html.twig');
            $userKey =  $loggedInUser->convertPasswordIntoUserKey($passwordOfLoggedInUser);
            $masterKey =  $loggedInUser->decrypt( $loggedInUser->getEncryptedMasterKey(),  $userKey);
            unset($passwordOfLoggedInUser);
            $user->setEncryptedMasterKey( $user->encrypt($masterKey, $user->convertPasswordIntoUserKey($user->getNewPassword()))  );

			$encoded = $encoder->encodePassword($user, $plainPassword);
			$user->setPassword($encoded);
			
			$this->getDoctrine()
				->getManager()
				->flush();

            // commented to avoid session -- $this->addFlash('success', 'Password changed.');
			
			return $this->redirectToRoute('user_change_pass', [
				'id' => $user->getId()
			]);
		}
		
		return $this->render('user/change_pass.html.twig', [
			'user' => $user,
			'form' => $form->createView()
		]);
	}

	/**
	 * @Route("/{id}", name="user_delete", methods="DELETE")
	 */
	public function delete(Request $request, User $user): Response
	{
		if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
			$em = $this->getDoctrine()->getManager();
			$em->remove($user);
			$em->flush();
            // commented to avoid session -- $this->addFlash('danger', 'Deleted.');
		}
		
		return $this->redirectToRoute('user_index');
	}
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">

    <button class="btn btn-danger">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/change_pass.html.twig
{% extends 'base.html.twig' %}

{% block title %}Change password{% endblock %}

{% block body %}
    <h1>Change password for <strong>{{ user }}</strong></h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="pull-right"><a href="{{ path('user_index') }}" class="btn btn-default">Back to list</a>
	</div>
  
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="pull-right"><a href="{{ path('user_index') }}" class="btn btn-default">Back to list</a>
	</div>
    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>Users</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Email</th>
                <th>Active</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.isActive ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}"  class="btn btn-default">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}"  class="btn btn-default">edit</a>
                    <a href="{{ path('user_change_pass', {'id': user.id}) }}" class="btn btn-default">change password</a>
                    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}" class="btn btn-default">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <div class="pull-right" ><a href="{{ path('user_index') }}" class="btn btn-default">back to list</a>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>IsActive</th>
                <td>{{ user.isActive ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{% for role in user.roles %}
                		{{ role }}<br>
                	{% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <div class="pull-right"><a href="{{ path('user_index') }}" class="btn btn-default">back to list</a></div>

    <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-primary">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}